import type { Metadata } from "next";
import localFont from "next/font/local";
import { Barlow } from "next/font/google";
import "./globals.css";
import GsapComponet from "@/components/Gsapcomp";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const boskaSans = localFont({
  src: "./fonts/BoskaVariable.ttf",
  variable: "--font-boska",
  preload:true,
  adjustFontFallback:"Times New Roman",
  weight: "100",

});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const barlowSans = Barlow({
  subsets: ["latin"],
  variable: "--font-barlow",
  weight: ["200", "300", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${boskaSans.variable} ${geistMono.variable} ${barlowSans.variable} antialiased`}
      >
        {children}
        {/* <GsapComponet/> */}
      </body>
    </html>
  );
}
